version: '3.1'

services:

  ecommerce-app:
    image: ecommerce-app:latest
    container_name: ecommerce-app
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    healthcheck:
      test: curl -f http://localhost:3000/api/status || exit 1
      interval: 1m
      timeout: 10s
      retries: 2

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongosecret
    volumes:
       - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongosecret
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongosecret@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
    