apiVersion: apps/v1
kind: Deployment
metadata:
  name: commercify-deployment
  labels:
    app: commercify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commercify
  template:
    metadata:
      labels:
        app: commercify
    spec:
      containers:
      - name: commercify
        image: ecommerce-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: commercify-service
spec:
  type: NodePort
  selector:
    app: commercify
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # same as container port
      nodePort: 30000